### ISSUE TITLE
Help, I'm a newbie, how can I make it work?

### ISSUE THREAD

**Issue by GodARG78** [aisyshk/HyperX-Battery#2]
I have a question, does it work for Hyper X Cloud Flight S? If so, how can I make it work? I'm getting several errors in the Visual Studio error list, like 'hid_device is not defined' or 'Cannot open include file: 'hidpi/hidapi.h': No such file or directory'.
![image](https://github.com/aisyshk/HyperX-Battery/assets/86077629/d67c32d3-2ae9-49de-8404-2516d38ee69e)
![image](https://github.com/aisyshk/HyperX-Battery/assets/86077629/2636bb27-0d22-4e65-885b-2c55a8cae3bc)
![image](https://github.com/aisyshk/HyperX-Battery/assets/86077629/68b60b07-595e-4c8f-a837-cd42097d106a)
Thank you in advance for your response!

**Comment by hux0192** [comment]
Using VCPKG or CMake, whichever package manager you have, download the `hidapi` package and then reference the folder, where you have your packages, in Visual Studio project settings.
